# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg325-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/CSE 401/Lab1/Lab1/Lab1.cache/wt} [current_project]
set_property parent.project_path {C:/CSE 401/Lab1/Lab1/Lab1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/CSE 401/Lab1/Lab1/Lab1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/CSE 401/Lab1/mux.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/CSE 401/Lab1/Lab1/Lab1.srcs/constrs_1/new/Lab1.xdc}}
set_property used_in_implementation false [get_files {{C:/CSE 401/Lab1/Lab1/Lab1.srcs/constrs_1/new/Lab1.xdc}}]


synth_design -top mux -part xc7a35tcsg325-1


write_checkpoint -force -noxdef mux.dcp

catch { report_utilization -file mux_utilization_synth.rpt -pb mux_utilization_synth.pb }
